repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt


# python3 -m venv .venv
# source .venv/bin/activate
# pip install pre-commit
# pre-commit install

