repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4
    hooks:
      - id: terraform_fmt
        args: [--args=-diff]
        exclude: '^(terraform/modules/|\.terraform/|\.tpl/)'
      - id: terraform_tflint
        args: [--args=--call-module-type=all]
        exclude: '^(terraform/modules/|\.terraform/|\.tpl/)'
      - id: terraform_trivy
        exclude: '^(terraform/modules/|\.terraform/|\.tpl/)'
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
        exclude: '^(terraform/modules/|\.terraform/|\.tpl/)'
      - id: terragrunt_validate
        files: '(terraform/prod\.hcl)$'
        exclude: '(\.terraform/.*|resources/terragrunt\.hcl)$'

  # terragrunt hcl fmt を最新のコマンドで動かすためのローカル hook
  - repo: local
    hooks:
      - id: terragrunt_hclfmt
        name: terragrunt hcl fmt
        entry: terragrunt hcl fmt
        language: system
        types: [hcl]
        files: \.hcl$
        exclude: '(\.terraform/.*|terraform/modules/|\.tpl/)'
