# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "minimal-gov-network-tfstate-ap-northeast-1-351277498040"
    encrypt = true
    key     = "db/terraform.tfstate"
    region  = "ap-northeast-1"
  }
}
