# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "aws-remotebackend-bootstrap-tfstate-ap-northeast-1-653502182074"
    encrypt      = true
    key          = "state/organization/terraform.tfstate"
    region       = "ap-northeast-1"
    use_lockfile = true
  }
}
