# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "minimal-gov-network-backend-tfstate-ap-northeast-1-854669817093"
    encrypt = true
    key     = "tgw_route/terraform.tfstate"
    region  = "ap-northeast-1"
  }
}
