name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t rtart/my-app:latest .

      - name: Docker Login to Docker Hub  # Docker Hub にログイン
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # GitHub Secrets に登録した Docker Hub ユーザー名
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # GitHub Secrets に登録した Docker Hub パスワード

      - name: Docker Push to Docker Hub  # Docker Hub に Push
        run: docker push rtart/my-app:latest 

      - name: SSH remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop my-app || true
            docker rm my-app || true
            docker pull rtart/my-app:latest 
            docker run -d --name my-app -p 80:5000 rtart/my-app:latest 
            echo "デプロイが成功しました！"