name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t rtart/my-app:latest .

      - name: Docker Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Push to Docker Hub
        run: docker push rtart/my-app:latest

      - name: SSH remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ↓↓↓ sudo を追加 ↓↓↓
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            sudo docker pull rtart/my-app:latest 
            sudo docker run -d --name my-app -p 80:5000 rtart/my-app:latest 
            echo "デプロイが成功しました！"