
name: terraform-ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform-ci.yml"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt_validate:
    name: fmt & validate (all dirs)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Terraform fmt (check, recursive)
        run: terraform fmt -check -diff -recursive

      - name: Validate all Terraform directories
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t DIRS < <(find . -type f -name "*.tf" -not -path "*/.terraform/*" -printf '%h\n' | sort -u)

          echo "Found ${#DIRS[@]} Terraform directories"
          for d in "${DIRS[@]}"; do
            echo "::group::Validating $d"
            terraform -chdir="$d" init -backend=false -input=false -upgrade
            terraform -chdir="$d" validate -no-color
            echo "::endgroup::"
          done
