name: Terraform Static CI

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TF_PLUGIN_CACHE_DIR: ${{ runner.temp }}/tf-plugin-cache
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.59.1

      - name: Prepare plugin cache dir
        run: mkdir -p "$TF_PLUGIN_CACHE_DIR"

      # 1) fmt（全ディレクトリを対象）
      - name: terraform fmt -check -recursive
        run: terraform fmt -check -recursive

      # 2) 各ディレクトリで init/validate/tflint を実行
      - name: init / validate / tflint per directory
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t DIRS < <(find . -type f -name '*.tf' -not -path '*/.terraform/*' -print0 \
            | xargs -0 -n1 dirname | sort -u)
          if [ ${#DIRS[@]} -eq 0 ]; then
            echo "No Terraform directories found."
            exit 0
          fi
          for d in "${DIRS[@]}"; do
            echo "===> ${d}"
            (
              cd "${d}"
              terraform init -backend=false -input=false >/dev/null
              terraform validate -no-color
              tflint --minimum-failure-severity=error --format=compact
            )
          done
